/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

CREATE TABLE IF NOT EXISTS  `ums_oh_invite` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `member_id` bigint(20) DEFAULT NULL,
  `mobile` varchar(255) DEFAULT NULL,
  `nick_name` varchar(50) DEFAULT NULL,
  `invite_code` varchar(20) DEFAULT NULL,
  `invite_level` int(20) DEFAULT '0',
  `invite_member_id` bigint(20) DEFAULT NULL,
  `invite_nick_name` varchar(50) DEFAULT NULL,
  `invite_mobile` varchar(20) DEFAULT NULL,
  `invite_num` int(20) DEFAULT '0',
  `invite_total` int(20) DEFAULT '0',
  `auth_num` int(20) DEFAULT '0',
  `auth_status` tinyint(1) DEFAULT '0',
  `depth_path` text,
  `depth` int(20) DEFAULT '0',
  `active_value` decimal(20,4) DEFAULT '0.0000',
  `active_a_value` decimal(20,4) DEFAULT '0.0000',
  `active_b_value` decimal(20,4) DEFAULT '0.0000',
  `team_level` int(20) DEFAULT '0',
  `team_active_value` decimal(20,4) DEFAULT '0.0000',
  `team_active_a_value` decimal(20,4) DEFAULT '0.0000',
  `team_active_b_value` decimal(20,4) DEFAULT '0.0000',
  `team_active_value_ext` decimal(20,4) DEFAULT '0.0000',
  `team_big_active_value` decimal(20,4) DEFAULT '0.0000',
  `team_small_active_value` decimal(20,4) DEFAULT '0.0000',
  `team_fee` decimal(20,4) DEFAULT '0.0000',
  `invite_fee` decimal(20,4) DEFAULT '0.0000',
  `ext` text,
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `ad_level` int(20) DEFAULT '0',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `index_member_id` (`member_id`) USING HASH,
  KEY `index_invite_code` (`invite_code`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
